/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WebTypewriter {
    'interval': number;
    'words': string;
  }
  interface WebTypewriterAttributes extends StencilHTMLAttributes {
    'interval'?: number;
    'words'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WebTypewriter': Components.WebTypewriter;
  }

  interface StencilIntrinsicElements {
    'web-typewriter': Components.WebTypewriterAttributes;
  }


  interface HTMLWebTypewriterElement extends Components.WebTypewriter, HTMLStencilElement {}
  var HTMLWebTypewriterElement: {
    prototype: HTMLWebTypewriterElement;
    new (): HTMLWebTypewriterElement;
  };

  interface HTMLElementTagNameMap {
    'web-typewriter': HTMLWebTypewriterElement
  }

  interface ElementTagNameMap {
    'web-typewriter': HTMLWebTypewriterElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
